WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 768
MENU_WIDTH = 200
SIM_WIDTH = WINDOW_WIDTH - MENU_WIDTH

CELL_SIZE = 8
COLS = SIM_WIDTH // CELL_SIZE
ROWS = WINDOW_HEIGHT // CELL_SIZE
FPS = 60
MIN_BRUSH_SIZE = 1
MAX_BRUSH_SIZE = 16
TOP_BAR_HEIGHT = 28
INTERACTION_MATRIX_FILE = "interaction_matrix.json"

CONSOLE_HEIGHT = 280
CONSOLE_MAX_LINES = 200
CONSOLE_FONT_SIZE = 13
CONSOLE_INPUT_COLOR = (180, 230, 180)
CONSOLE_OUTPUT_COLOR = (220, 220, 220)
CONSOLE_ERROR_COLOR = (255, 100, 80)
CONSOLE_SYSTEM_COLOR = (140, 200, 255)
CONSOLE_PROMPT = ">>> "
CONSOLE_CONT_PROMPT = "... "
CONFIG_PROFILES_FILE = "config_profiles.json"
SNAPSHOT_BASELINE_FILE = "snapshot_baselines.json"
