from dataclasses import dataclass, field
import numpy as np


def _zeros(shape=(0, 0), dtype=np.float32):
    return np.zeros(shape, dtype=dtype)


@dataclass
class SimulationState:
    lateral_bias: list = field(default_factory=list)
    jammed_until: list = field(default_factory=list)
    fluid_pressure: np.ndarray = field(default_factory=_zeros)
    mix_ratio: np.ndarray = field(default_factory=_zeros)
    temperature: np.ndarray = field(default_factory=_zeros)
    oxygen_level: np.ndarray = field(default_factory=_zeros)
    burn_stage: np.ndarray = field(default_factory=_zeros)
    burn_progress: np.ndarray = field(default_factory=_zeros)
    smoke_density: np.ndarray = field(default_factory=_zeros)
    ignition_cooldown_until: np.ndarray = field(default_factory=_zeros)
    fire_lifetime: np.ndarray = field(default_factory=_zeros)
    moisture: np.ndarray = field(default_factory=_zeros)
    smoke_lifetime: np.ndarray = field(default_factory=_zeros)
    enthalpy_field: np.ndarray = field(default_factory=_zeros)
    liquid_fraction: np.ndarray = field(default_factory=_zeros)
    steam_density: np.ndarray = field(default_factory=_zeros)
    integrity: np.ndarray = field(default_factory=_zeros)
    saturation_level: np.ndarray = field(default_factory=_zeros)
    phase_state: np.ndarray = field(default_factory=_zeros)
    reaction_progress: np.ndarray = field(default_factory=_zeros)
    phase_cooldown_until: np.ndarray = field(default_factory=_zeros)
    phase_transition_progress: np.ndarray = field(default_factory=_zeros)
    phase_transition_target: np.ndarray = field(default_factory=_zeros)
    fuel_vapor: np.ndarray = field(default_factory=_zeros)
    co2_density: np.ndarray = field(default_factory=_zeros)
    co_density: np.ndarray = field(default_factory=_zeros)
    h2o_vapor: np.ndarray = field(default_factory=_zeros)
    mixture_fraction: np.ndarray = field(default_factory=_zeros)
    turb_k: np.ndarray = field(default_factory=_zeros)
    turb_eps: np.ndarray = field(default_factory=_zeros)
    pyrolysis_progress: np.ndarray = field(default_factory=_zeros)
    soot_mass_fraction: np.ndarray = field(default_factory=_zeros)
    soot_number_density: np.ndarray = field(default_factory=_zeros)
    h_plus: np.ndarray = field(default_factory=_zeros)
    oh_minus: np.ndarray = field(default_factory=_zeros)
    ph_field: np.ndarray = field(default_factory=_zeros)
    catalyst_theta_fuel: np.ndarray = field(default_factory=_zeros)
    catalyst_theta_o2: np.ndarray = field(default_factory=_zeros)
    disp_x: np.ndarray = field(default_factory=_zeros)
    disp_y: np.ndarray = field(default_factory=_zeros)
    struct_vel_x: np.ndarray = field(default_factory=_zeros)
    struct_vel_y: np.ndarray = field(default_factory=_zeros)
    sigma_xx: np.ndarray = field(default_factory=_zeros)
    sigma_yy: np.ndarray = field(default_factory=_zeros)
    tau_xy: np.ndarray = field(default_factory=_zeros)
    plastic_strain: np.ndarray = field(default_factory=_zeros)
    damage_field: np.ndarray = field(default_factory=_zeros)
    pore_pressure: np.ndarray = field(default_factory=_zeros)
    debris_particles: list = field(default_factory=list)
    vel_x: np.ndarray = field(default_factory=_zeros)
    vel_y: np.ndarray = field(default_factory=_zeros)
    pressure_pde: np.ndarray = field(default_factory=_zeros)
    divergence_pde: np.ndarray = field(default_factory=_zeros)
    density_field: np.ndarray = field(default_factory=_zeros)
    active_mask: np.ndarray = field(default_factory=lambda: np.zeros((0, 0), dtype=np.bool_))
    mac_u: np.ndarray = field(default_factory=_zeros)
    mac_v: np.ndarray = field(default_factory=_zeros)
    acoustic_pressure: np.ndarray = field(default_factory=_zeros)
    acoustic_u: np.ndarray = field(default_factory=_zeros)
    acoustic_v: np.ndarray = field(default_factory=_zeros)
    porous_resistance: np.ndarray = field(default_factory=_zeros)
    em_ex: np.ndarray = field(default_factory=_zeros)
    em_ey: np.ndarray = field(default_factory=_zeros)
    em_bz: np.ndarray = field(default_factory=_zeros)
    current_x: np.ndarray = field(default_factory=_zeros)
    current_y: np.ndarray = field(default_factory=_zeros)
    joule_heating_source: np.ndarray = field(default_factory=_zeros)
    pending_detonations: list = field(default_factory=list)
    work_buffers: dict = field(default_factory=dict)
